---

    - name: Install Prerequisites
      apt: >
        name={{ item }}
        state=installed
      with_items: 
        - build-essential
        - python-dev
        - libevent-dev
        - python-pip
        - liblzma-dev

    - name: Install and Configure Docker Registry
      pip: name=docker-registry

    - file: path=/var/lib/docker-registry state=directory

    - name: copy docker-registry configuration file
      copy: src=config.yml dest=/usr/local/lib/python2.7/dist-packages/config/config.yml
      notify: restart docker-registry

    - file: path=/var/log/docker-registry state=directory

    - copy: src=docker-registry.conf dest=/etc/init/
      notify: restart docker-registry

    - name: Secure Docker Registry with Nginx
      apt: >
        name={{item}}
        state=installed
      with_items:
        - nginx
        - python-passlib
        - openssl

    - file: path=/etc/nginx/ssl state=directory

#    - name: create root key and certificate
#      command: openssl req -new -nodes -x509 -subj "/C=/ST=/L=/O=/CN={{ansible_hostname}}" -days 3650 -keyout /etc/nginx/ssl/ca.key -out /etc/nginx/ssl/ca.crt

    - name: stat docker-registry certificate file
      stat: path=/etc/nginx/ssl/server.crt
      register: docker_registry_cert_stat

    - name: create server key and certificate
      command: openssl req -new -nodes -x509 -subj "/C=/ST=/L=/O=/CN={{docker_registry_host}}" -days 3650 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca creates=/etc/nginx/ssl/server.crt
      when: not docker_registry_cert_stat.stat.exists
      notify: restart nginx

    - htpasswd: path=/etc/nginx/docker-registry.htpasswd name={{item.name}} password={{item.password}} owner=root group=root mode=0644
      with_items: users

    - copy: src=nginx-docker-registry.conf dest=/etc/nginx/docker-registry.conf
      notify: restart docker-registry

    - template: src=docker-registry.j2 dest=/etc/nginx/sites-available/docker-registry owner=root group=root mode=0644

    - file: src=/etc/nginx/sites-available/docker-registry dest=/etc/nginx/sites-enabled/docker-registry state=link
      notify: restart nginx
