---

  # We must install pip before we can use the pip module below
  - easy_install: name=pip #state=latest required ansible 2.x
    environment: "{{proxy_env}}"
    sudo: yes

  # Upgrade pip to fix docker-py/issues/525
  # Install latest version when no specific release is set.
  - name: Upgrade latest pip, setuptools, and docker-py with pip
    pip:
      name: "{{ item.name }}"
      state: latest
      extra_args: "{{ pip_extra_args }}"
    with_items:
      - { name: pip, version: "{{ pip.version.pip }}" }
      - { name: setuptools, version: "{{ pip.version.setuptools }}" }
      - { name: six, version: "{{ pip.version.six }}" }
      - { name: docker-py, version: "{{ pip.version.docker_py }}" }
    sudo: yes
    when: item.version=="latest"

  # Install specific version when set in the variables
  - name: Install specific pip, setuptools, and docker-py with pip
    pip:
      name: "{{ item.name }}"
      state: present
      version: "{{ item.version }}"
      extra_args: "{{ pip_extra_args }}"
    with_items:
      - { name: pip, version: "{{ pip.version.pip }}" }
      - { name: setuptools, version: "{{ pip.version.setuptools }}" }
      - { name: six, version: "{{ pip.version.six }}" }
      - { name: docker-py, version: "{{ pip.version.docker_py }}" }
    sudo: yes
    when: item.version!="latest"
